/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp CommandInterface.xml -p CommandInterfaceProxy -i CommandInterface.h -N -c CommandInterface
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "CommandInterfaceProxy.h"

/*
 * Implementation of interface class CommandInterface
 */

CommandInterface::CommandInterface(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

CommandInterface::~CommandInterface()
{
}

